name: Audit Kubernetes Manifests

on:
  pull_request:
    paths:
      - bases/**/*.yaml
      - environments/**/*.yaml

  push:
    branches:
      - main
      - master
    paths:
      - bases/**/*.yaml
      - environments/**/*.yaml

jobs:
  gatekeeper-policy-compliance:
    if: github.repository_owner == 'thousandeyes'
    runs-on: ubuntu-latest
    steps:
      - name: Gatekeeper Policy Compliance Check
        uses: thousandeyes/gh-action-kubernetes-audit@v1
        with:
          ssh_key: ${{ secrets.EE_GITOPS_SSH_KEY }}